#!/usr/bin/env python
#
#SOSCleaner Executable

from SOSCleaner import SOSCleaner
from optparse import OptionParser

version = '0.1'

def main():

    parser = OptionParser(usage="%prog -s [-l -c -r -x]" )
    parser.add_option("-l", "--log_level", dest="loglevel", default='INFO', help="The Desired Log Level (default = INFO) Options are DEBUG, INFO, WARNING, ERROR", metavar="LOGLEVEL")
    parser.add_option("-c", "--compress", action="store_true", default=True, dest="compress", help="If used, will tar and gzip the output", metavar="COMPRESS")
    parser.add_option("-r", "--reporting", action="store_true", default=False, dest="reporting", help="Create CSV output for IP and Hostname databases", metavar="REPORTING")
    parser.add_option("-s", "--sosreport", dest="sosreport", help="The SOSReport that is to be cleaned", metavar="SOSREPORT")
    parser.add_option("-x", "--xsos", action="store_true", default=False, help="XSOS-Style Summary data (COMING SOON!)")

    (options, args) = parser.parse_args()

    cleaner = SOSCleaner(sosreport=options.sosreport, compress=options.compress, loglevel=options.loglevel, reporting=options.reporting, xsos=options.xsos)
    cleaner.clean_report()

if __name__ == '__main__':
    main()

