#!/usr/bin/env python
#
#SOSCleaner Executable

from SOSCleaner import SOSCleaner
from optparse import OptionParser
import sys

version = '0.1'

def main():

    parser = OptionParser(usage="%prog [-l-r] /path/to/sosreport" )
    parser.add_option("-l", "--log_level", dest="loglevel", default='INFO', help="The Desired Log Level (default = INFO) Options are DEBUG, INFO, WARNING, ERROR", metavar="LOGLEVEL")
    parser.add_option("-r", "--reporting", action="store_true", default=False, dest="reporting", help="Create CSV output for IP and Hostname databases (enabled by default)", metavar="REPORTING")

    (options, args) = parser.parse_args()
    if not args:
        parser.print_help()
        sys.exit(1)
    sosreport = args[0] #grab the sosreport path
    cleaner = SOSCleaner(options, sosreport)
    cleaner.clean_report()

if __name__ == '__main__':
    main()

